# Arrays vs Lists

In [2]:
import numpy as np

In [4]:
pythonL = [1,2,3]
numpyA = np.array([1,2,3])

### For Loops work as expected

In [5]:
for x in pythonL:
    print(x)

1
2
3


In [6]:
for x in numpyA:
    print(x)

1
2
3


### Append doesn't work on a numpy array because, think of it as an array vs a list. size of array is fixed!

In [7]:
pythonL.append(4)
pythonL

[1, 2, 3, 4]

In [8]:
numpyA.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

### The + works as concatenation of two lists in Python and as Numpy is more of math, it adds the element 4 to all the items of the numpy array. This behaviour is also called as broadcasting. Notice that only vectors of same size can be added. When initially adding 4, it is actually an np array of [4,4,4,]

In [10]:
pythonL + [5]
pythonL

[1, 2, 3, 4]

In [11]:
numpyA + np.array([4])

array([5, 6, 7])

In [12]:
numpyA + np.array([4,5,6])

array([5, 7, 9])

In [13]:
numpyA + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### To add the elements as expected in Python, there's either for loop or list comprehension

In [18]:
pythonL2 = [e + 4 for e in pythonL]
pythonL2

[5, 6, 7, 8]

### If you apply a function to a numpy array, it operates element wise 

In [14]:
2 * numpyA

array([2, 4, 6])

In [21]:
np.array([3,4,5]) * numpyA

array([ 3,  8, 15])

In [22]:
numpyA ** 2

array([1, 4, 9])

In [23]:
np.sqrt(numpyA)

array([1.        , 1.41421356, 1.73205081])

In [24]:
np.log(numpyA)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(numpyA)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [15]:
2 * pythonL

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
pythonL + pythonL

[1, 2, 3, 4, 1, 2, 3, 4]

## A List looks like an Numpy array but is a generic data structure, where as a Numpy Array is built to do math.